### ISSUE TITLE
[REQUEST] Add Audio Driver info and supported audio formats

### ISSUE THREAD

**Issue by peppemas** [Kode/Kore#491]
Hello, 

As videoformats() it could useful to have a list of supported audio formats and audio driver used to play. 

https://github.com/Kode/Kinc/blob/3575bcdc48b1dc7dd6ed16d62b292453d6793a8b/Sources/Kore/System.h#L26

**Comment by RobDangerous** [comment]
Audio formats isn't needed because it's the same everywhere (wav and ogg). Video formats is different per system because the system's video APIs are used for hardware-accelerated decoding. For audio-driver info please have a look at kinc_a2_buffer_format_t, that includes all the info you need from the driver.
